apiVersion: apps/v1
kind: Deployment
metadata:
  name: moon-facts-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moon-facts
  template:
    metadata:
      labels:
        app: moon-facts
    spec:
      containers:
      - name: moon-facts
        image: 533266979424.dkr.ecr.us-east-1.amazonaws.com/moon-facts-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: moon-facts-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: moon-facts
